name: 'regional_data_convergence'
version: '1.0.0'
config-version: 2
profile: "cbr"

model-paths: ['models']
seed-paths: ['seeds']
test-paths:
  - "tests"
target-path: 'target'
clean-targets:
  - 'target'

models:
  regional_data_convergence:
    staging:
      materialized: view
    marts:
      materialized: table