name: 'regional_data_convergence'
version: '1.0.0'
config-version: 2
profile: "cbr"
require-dbt-version: [">=1.7.9", "<1.10.0"]

model-paths: ['models']
snapshot-paths: ["snapshots"]
seed-paths: ['seeds']
test-paths:
  - "tests"
target-path: 'target'
clean-targets:
  - 'target'

models:
  regional_data_convergence:
    pre-hook:
      - "INSERT INTO audit.logs (event, timestamp) VALUES ('# Delta model: {{ this.name }}',  CURRENT_TIMESTAMP())"
    post-hook:
      - "INSERT INTO audit.logs (event, timestamp, new_rows) VALUES ('# Full model: {{ this.name }}',  CURRENT_TIMESTAMP(), (SELECT COUNT(*) FROM {{ this }}))"
    staging:
      materialized: view
    marts:
      materialized: table