name: 'regional_data_convergence'
version: '1.0.0'
config-version: 2

model-paths: ['models']
seed-paths: ['seeds']
target-path: 'target'
clean-targets:
  - 'target'

models:
  regional_data_convergence:
    materialized: table